version: '3'

volumes:

  produto-ms-data: { }

services:

  produto-ms-postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_DB: produto-ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
    ports:
      - 5432:5432
    volumes:
      - produto-ms-data:/var/lib/postgresql

  produto-ms:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: senior/produto-ms
    container_name: senior-produto-ms
    ports:
      - "9999:9999"
    depends_on:
      - "produto-ms-postgres"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24